const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const UNIT_BOUNDS=[[-122.18,49.19],[-121.70,49.69]], CENTER=[-121.94,49.44];
const COUNTS={boundary:1,roads:3888,cutblocks:2920,hydro:2478,vegetation:7497,wetlands:57,fires:46};
let exag=1.25, analysisMode='none', dataReady=false;
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e.t);e.t=setTimeout(()=>e.classList.remove('show'),1800)};

const map=new maplibregl.Map({container:'map',center:CENTER,zoom:9.55,pitch:62,bearing:-18,maxPitch:85,style:{version:8,sources:{sat:{type:'raster',tiles:['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],tileSize:256,attribution:'Esri'},topo:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'OpenStreetMap'},dem:{type:'raster-dem',tiles:['https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png'],tileSize:256,encoding:'terrarium',maxzoom:15}},layers:[{id:'sat',type:'raster',source:'sat'},{id:'topo',type:'raster',source:'topo',layout:{visibility:'none'}},{id:'hillshade',type:'hillshade',source:'dem',paint:{'hillshade-exaggeration':.38}}]}});
map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'bottom-right');
map.addControl(new maplibregl.ScaleControl({unit:'metric'}),'bottom-left');

const sources={"boundary": ["zone_boundary", ["zone_boundary.0.txt"]], "roads": ["roads", ["roads.0.txt", "roads.1.txt"]], "cutblocks": ["cutblocks", ["cutblocks.0.txt", "cutblocks.1.txt", "cutblocks.2.txt"]], "hydro": ["hydro", ["hydro.0.txt"]], "vegetation": ["vri_vegetation", ["vri_vegetation.0.txt", "vri_vegetation.1.txt", "vri_vegetation.2.txt", "vri_vegetation.3.txt", "vri_vegetation.4.txt"]], "wetlands": ["wetlands", ["wetlands.0.txt"]], "fires": ["historical_fires", ["historical_fires.0.txt"]]};
const layerIds={boundary:['zone-fill','zone-line'],roads:['roads-line'],cutblocks:['cuts-fill','cuts-line'],hydro:['hydro-line'],vegetation:['veg-fill'],wetlands:['wet-fill'],fires:['fires-fill']};
async function loadPacked(files){const chunks=await Promise.all(files.map(file=>fetch('data/'+file,{cache:'force-cache'}).then(r=>{if(!r.ok)throw Error(file+' '+r.status);return r.text()})));const txt=chunks.join('');const bin=atob(txt.trim());const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);const json=pako.ungzip(bytes,{to:'string'});return JSON.parse(json)}
async function addData(){
 $('#loadingText').textContent='Loading embedded GIS layers…';
 const entries=await Promise.all(Object.entries(sources).map(async([group,[src,file]])=>[group,src,await loadPacked(file)]));
 for(const [group,src,data] of entries) map.addSource(src,{type:'geojson',data});
 map.addLayer({id:'zone-fill',type:'fill',source:'zone_boundary',paint:{'fill-color':'#e2c351','fill-opacity':.025}});
 map.addLayer({id:'zone-line',type:'line',source:'zone_boundary',paint:{'line-color':'#e2c351','line-width':['interpolate',['linear'],['zoom'],8,1.5,14,3.2]}});
 map.addLayer({id:'veg-fill',type:'fill',source:'vri_vegetation',layout:{visibility:'none'},paint:{'fill-color':['match',['get','veg_age_class'],'open_nonforest','#d6d0bc','0_20','#bddca8','21_40','#93c77e','41_80','#68a968','81_140','#447c53','141_plus','#235237','#888'],'fill-opacity':.34}});
 map.addLayer({id:'fires-fill',type:'fill',source:'historical_fires',layout:{visibility:'none'},paint:{'fill-color':['match',['get','fire_period'],'2020_2025','#c84636','2000_2019','#df6b45','1980_1999','#e99b58','pre_1980','#b99b68','#d26c4e'],'fill-opacity':.3}});
 map.addLayer({id:'cuts-fill',type:'fill',source:'cutblocks',paint:{'fill-color':['match',['get','age_class'],'0_5','#f4d43f','6_10','#ef9e37','11_15','#9dce72','16_20','#5a9a60','21_plus','#7b7b75','#aaa'],'fill-opacity':.48}});
 map.addLayer({id:'cuts-line',type:'line',source:'cutblocks',paint:{'line-color':'rgba(255,255,255,.28)','line-width':['interpolate',['linear'],['zoom'],9,.2,15,1.0]}});
 map.addLayer({id:'wet-fill',type:'fill',source:'wetlands',layout:{visibility:'none'},paint:{'fill-color':'#6bc9d2','fill-opacity':.48,'fill-outline-color':'#b8f3f4'}});
 map.addLayer({id:'hydro-line',type:'line',source:'hydro',paint:{'line-color':['match',['get','water_type'],'rivers','#3f93c8','#75b9dc'],'line-width':['interpolate',['linear'],['zoom'],8,.4,15,2.0]}});
 map.addLayer({id:'roads-line',type:'line',source:'roads',paint:{'line-color':['match',['get','access_class'],'likely_driveable','#51c56b','maybe_check_access','#f0a13c','overgrown_deactivated','#e45850','trail_nonroad','#9b6bd0','unknown','#9c9c9c','#888'],'line-width':['interpolate',['linear'],['zoom'],8,.4,12,1.0,15,2.5],'line-opacity':.97}});
 dataReady=true; $('#featureCount').textContent='16,887 features'; $('#loading').style.display='none'; toast('Chehalis layers loaded');
}
function setGroup(group,on){for(const id of layerIds[group]||[])if(map.getLayer(id))map.setLayoutProperty(id,'visibility',on?'visible':'none')}
function checkbox(group,on){const el=$(`input[data-group="${group}"]`);if(el){el.checked=on;setGroup(group,on)}}
function resetFilters(){if(map.getLayer('cuts-fill')){map.setFilter('cuts-fill',null);map.setFilter('cuts-line',null);map.setPaintProperty('cuts-fill','fill-opacity',.48);map.setPaintProperty('cuts-line','line-color','rgba(255,255,255,.28)')}if(map.getLayer('roads-line'))map.setFilter('roads-line',null);if(map.getLayer('veg-fill'))map.setFilter('veg-fill',null)}
function ageClass(q){if(/\b0\s*(?:-|–|to)\s*5\b|\b1\s*(?:-|–|to)\s*5\b|\b1\s*(?:-|–|to)\s*5\s*year/.test(q))return'0_5';if(/\b6\s*(?:-|–|to)\s*10\b/.test(q))return'6_10';if(/\b11\s*(?:-|–|to)\s*15\b/.test(q))return'11_15';if(/\b16\s*(?:-|–|to)\s*20\b/.test(q))return'16_20';if(/\b21\s*\+|21\s*(?:and|or)\s*older/.test(q))return'21_plus';return null}
function roadClass(q){if(/likely driveable|likely drivable|driveable roads|drivable roads/.test(q))return'likely_driveable';if(/maybe|check access/.test(q))return'maybe_check_access';if(/overgrown|deactivated/.test(q))return'overgrown_deactivated';if(/trail|non[- ]road/.test(q))return'trail_nonroad';if(/unknown roads?/.test(q))return'unknown';return null}
function runCommand(raw){const q=raw.trim().toLowerCase().replace(/[–—]/g,'-');if(!q){$('#cmdStatus').textContent='Type a command';return}if(!dataReady){$('#cmdStatus').textContent='Layers are still loading…';return}
 if(/reset|default view|start over/.test(q)){resetFilters();['boundary','roads','cutblocks','hydro'].forEach(g=>checkbox(g,true));['vegetation','wetlands','fires'].forEach(g=>checkbox(g,false));setAnalysis('none');map.fitBounds(UNIT_BOUNDS,{padding:45,pitch:58,bearing:-18,duration:800});$('#cmdStatus').textContent='Reset complete';return}
 const age=ageClass(q);if(age&&(q.includes('cut')||q.includes('year'))){checkbox('cutblocks',true);map.setFilter('cuts-fill',['==',['get','age_class'],age]);map.setFilter('cuts-line',['==',['get','age_class'],age]);map.setPaintProperty('cuts-fill','fill-opacity',.82);map.setPaintProperty('cuts-line','line-color','#fff3a6');const label={'0_5':'0–5','6_10':'6–10','11_15':'11–15','16_20':'16–20','21_plus':'21+'}[age];const n={'0_5':125,'6_10':283,'11_15':524,'16_20':307,'21_plus':1681}[age];$('#cmdStatus').textContent=`Highlighted ${n} cutblocks aged ${label} years`;toast(`${label} year cutblocks highlighted`);return}
 const rc=roadClass(q);if(rc&&(q.includes('road')||q.includes('access')||q.includes('trail')||q.includes('drive'))){checkbox('roads',true);map.setFilter('roads-line',['==',['get','access_class'],rc]);const n={likely_driveable:774,maybe_check_access:1838,overgrown_deactivated:1000,trail_nonroad:166,unknown:110}[rc];$('#cmdStatus').textContent=`Showing ${n} ${rc.replaceAll('_',' ')} features`;return}
 if(/slope/.test(q)){setAnalysis('slope');$('#cmdStatus').textContent='Slope analysis enabled';return}if(/aspect/.test(q)){setAnalysis('aspect');$('#cmdStatus').textContent='Aspect analysis enabled';return}if(/normal terrain|turn off analysis/.test(q)){setAnalysis('none');$('#cmdStatus').textContent='Normal terrain';return}
 if(/whole unit|overview|zoom out/.test(q)){map.fitBounds(UNIT_BOUNDS,{padding:45,pitch:58,bearing:-18,duration:800});$('#cmdStatus').textContent='Showing whole unit';return}
 if(/top[- ]down|2d/.test(q)){map.easeTo({pitch:0,bearing:0});$('#cmdStatus').textContent='Top-down view';return}
 const groupPatterns={cutblocks:/cutblocks?|cuts/,roads:/roads?|access/,hydro:/streams?|rivers?|water/,vegetation:/forest|vegetation|vri/,wetlands:/wetlands?/,fires:/fires?/,boundary:/boundary/};let changed=[];for(const[g,re]of Object.entries(groupPatterns)){if(re.test(q)){if(/hide|turn off|remove/.test(q)){checkbox(g,false);changed.push(`${g} off`)}else if(/show|turn on|display|highlight/.test(q)){checkbox(g,true);changed.push(`${g} on`)}}}if(/streams?.*wetlands?|wetlands?.*streams?|show water/.test(q)){checkbox('hydro',true);checkbox('wetlands',true);changed=['water layers on']}if(changed.length){$('#cmdStatus').textContent='Done — '+changed.join(', ');return}
 $('#cmdStatus').textContent='Try “highlight 1-5 year cutblocks” or “show driveable roads”';}
function setAnalysis(mode){analysisMode=mode;$$('[data-analysis]').forEach(b=>b.classList.toggle('active',b.dataset.analysis===mode));if(mode==='none'){map.setPaintProperty('hillshade','hillshade-shadow-color','#000');map.setPaintProperty('hillshade','hillshade-highlight-color','#fff');map.setPaintProperty('sat','raster-saturation',0);return}if(mode==='slope'){map.setPaintProperty('sat','raster-saturation',-.65);map.setPaintProperty('hillshade','hillshade-shadow-color','#481d1d');map.setPaintProperty('hillshade','hillshade-highlight-color','#eddc91');toast('Slope view: steeper terrain is emphasized by relief')}else{map.setPaintProperty('sat','raster-saturation',-.35);map.setPaintProperty('hillshade','hillshade-shadow-color','#1c2844');map.setPaintProperty('hillshade','hillshade-highlight-color','#d4bd7d');toast('Aspect-oriented terrain shading enabled')}}
function terrainReadout(e){try{const z=map.queryTerrainElevation(e.lngLat);if(!Number.isFinite(z))return;const lat=e.lngLat.lat,lng=e.lngLat.lng,d=0.00055;const eE=map.queryTerrainElevation([lng+d,lat]),eW=map.queryTerrainElevation([lng-d,lat]),eN=map.queryTerrainElevation([lng,lat+d]),eS=map.queryTerrainElevation([lng,lat-d]);let slope='—',aspect='—';if([eE,eW,eN,eS].every(Number.isFinite)){const mLon=111320*Math.cos(lat*Math.PI/180)*d,mLat=111320*d,dx=(eE-eW)/(2*mLon),dy=(eN-eS)/(2*mLat);const s=Math.atan(Math.hypot(dx,dy))*180/Math.PI;slope=s.toFixed(1)+'°';let a=(Math.atan2(dx,dy)*180/Math.PI+180+360)%360;aspect=['N','NE','E','SE','S','SW','W','NW'][Math.round(a/45)%8]}$('#readout').innerHTML=`<b>Elev</b> ${Math.round(z/exag)} m &nbsp; <b>Slope</b> ${slope} &nbsp; <b>Aspect</b> ${aspect}`}catch{}}
function inspect(e){const ids=['roads-line','cuts-fill','hydro-line','veg-fill','wet-fill','fires-fill','zone-line'].filter(id=>map.getLayer(id));const fs=map.queryRenderedFeatures(e.point,{layers:ids});if(!fs.length){$('#inspect').hidden=true;return}const f=fs[0],p=f.properties||{};let rows='';for(const[k,v]of Object.entries(p)){if(v!==null&&v!==''&&k!=='description')rows+=`<div class="row"><b>${k.replaceAll('_',' ')}</b><span>${v}</span></div>`}$('#inspectBody').innerHTML=rows||'<div>No attributes</div>';$('#inspect').hidden=false}

map.on('load',async()=>{map.setTerrain({source:'dem',exaggeration:exag});try{await addData()}catch(err){console.error(err);$('#loadingText').textContent='Layer load failed — refresh the page';$('#cmdStatus').textContent='Layer load failed';}});
map.on('mousemove',terrainReadout);map.on('click',inspect);
$$('input[data-group]').forEach(el=>el.addEventListener('change',()=>setGroup(el.dataset.group,el.checked)));
$('#homeBtn').onclick=()=>map.fitBounds(UNIT_BOUNDS,{padding:45,pitch:58,bearing:-18,duration:800});$('#topBtn').onclick=()=>map.easeTo({pitch:0,bearing:0});$('#northBtn').onclick=()=>map.easeTo({pitch:60,bearing:0});
$$('[data-base]').forEach(b=>b.onclick=()=>{$$('[data-base]').forEach(x=>x.classList.toggle('active',x===b));map.setLayoutProperty('sat','visibility',b.dataset.base==='sat'?'visible':'none');map.setLayoutProperty('topo','visibility',b.dataset.base==='topo'?'visible':'none')});
$$('[data-analysis]').forEach(b=>b.onclick=()=>setAnalysis(b.dataset.analysis));$('#exag').oninput=e=>{exag=+e.target.value;$('#exagOut').textContent=exag.toFixed(2)+'×';map.setTerrain({source:'dem',exaggeration:exag})};
const run=()=>runCommand($('#cmd').value);$('#run').onclick=run;$('#cmd').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();run()}});$$('[data-cmd]').forEach(b=>b.onclick=()=>{$('#cmd').value=b.dataset.cmd;runCommand(b.dataset.cmd)});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#cmd').focus();$('#cmd').select()}});$('#closeInspect').onclick=()=>$('#inspect').hidden=true;
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){const rec=new SR();rec.lang='en-CA';rec.interimResults=false;$('#mic').onclick=()=>{try{$('#cmdStatus').textContent='Listening…';rec.start()}catch{}};rec.onresult=e=>{$('#cmd').value=e.results[0][0].transcript;runCommand($('#cmd').value)};rec.onerror=()=>$('#cmdStatus').textContent='Mic unavailable — use Wispr Flow';}else $('#mic').onclick=()=>{$('#cmd').focus();$('#cmdStatus').textContent='Use Wispr Flow while this field is focused';};
